# .github/workflows/lint.yml
name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  stylua:
    name: Check Lua code style with stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Run stylua check
        uses: JohnnyMorganz/stylua-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check . # Explicitly tell stylua to check the current directory
