# .github/workflows/lint.yml
name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  stylua:
    name: Check Lua code style with stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # args: --check . # stylua action runs check by default

      - name: Run lint check via Makefile
        run: make lint # Use Makefile target
