# .github/workflows/test.yml
name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout

      - name: Set up Neovim
        uses: rhysd/action-setup-vim
        with:
          neovim: true
          version: stable # Or specify a version like 'v0.9.5'

      - name: Run tests
        run: make test # Use Makefile target
